// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vblqvkqkmdmlcxxphwks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZibHF2a3FrbWRtbGN4eHBod2tzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzI2NzIsImV4cCI6MjA3MjMwODY3Mn0.lej_UQn8W9c5vOL8VkizRonuWpsy8UKjfMjUhannHBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});